# Generated by Django 4.2.4 on 2025-01-28 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Furniture', 'Furniture'), ('Vehicle', 'Vehicle'), ('Electronics', 'Electronics'), ('Appliances', 'Appliances'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Sports', 'Sports'), ('Toys', 'Toys'), ('Jewelry', 'Jewelry'), ('Home Decor', 'Home Decor'), ('Garden', 'Garden'), ('Other', 'Other')], default='Mobile', max_length=50)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Used', 'Used'), ('Refurbished', 'Refurbished')], default='Used', max_length=50)),
                ('images', models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/%d/')),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_available', models.BooleanField(default=False)),
                ('negotiable', models.BooleanField(default=False)),
                ('other_details', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='home.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='additional_listings', to='home.listingimage'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
